/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface StorageInterface extends utils.Interface {
  functions: {
    "retrieve(address)": FunctionFragment;
    "store(address,uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "retrieve" | "store"): FunctionFragment;

  encodeFunctionData(functionFragment: "retrieve", values: [string]): string;
  encodeFunctionData(
    functionFragment: "store",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "retrieve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "store", data: BytesLike): Result;

  events: {};
}

export interface Storage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: StorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    retrieve(
      depositor: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    store(
      depositor: string,
      val: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  retrieve(depositor: string, overrides?: CallOverrides): Promise<BigNumber>;

  store(
    depositor: string,
    val: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    retrieve(depositor: string, overrides?: CallOverrides): Promise<BigNumber>;

    store(
      depositor: string,
      val: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    retrieve(depositor: string, overrides?: CallOverrides): Promise<BigNumber>;

    store(
      depositor: string,
      val: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    retrieve(
      depositor: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    store(
      depositor: string,
      val: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
